configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDdhNzRkZTU4NGQyMWYzZTEzOWI5YzUwNjFiYjM3NjE0MjhmMzFjMzhlOGMyYWY0NzY0NmJhMThmNDllMTRiYjMxM2RhZWRlZjg5OTBkNjExYmIyYWRmZTQ0ZWQ0MjU1NDdiNDU1NjNlNWY1MWFiY2M3MGM0NGU1OTMzMGJjODc=
