package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiRequestLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiRequestLogAllPropertiesEquals(ApiRequestLog expected, ApiRequestLog actual) {
        assertApiRequestLogAutoGeneratedPropertiesEquals(expected, actual);
        assertApiRequestLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiRequestLogAllUpdatablePropertiesEquals(ApiRequestLog expected, ApiRequestLog actual) {
        assertApiRequestLogUpdatableFieldsEquals(expected, actual);
        assertApiRequestLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiRequestLogAutoGeneratedPropertiesEquals(ApiRequestLog expected, ApiRequestLog actual) {
        assertThat(actual)
            .as("Verify ApiRequestLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiRequestLogUpdatableFieldsEquals(ApiRequestLog expected, ApiRequestLog actual) {
        assertThat(actual)
            .as("Verify ApiRequestLog relevant properties")
            .satisfies(a -> assertThat(a.getTransactionId()).as("check transactionId").isEqualTo(expected.getTransactionId()))
            .satisfies(a -> assertThat(a.getRequestedBy()).as("check requestedBy").isEqualTo(expected.getRequestedBy()))
            .satisfies(a -> assertThat(a.getRequestedOn()).as("check requestedOn").isEqualTo(expected.getRequestedOn()))
            .satisfies(a -> assertThat(a.getNumberOfRecords()).as("check numberOfRecords").isEqualTo(expected.getNumberOfRecords()))
            .satisfies(a -> assertThat(a.getRequestType()).as("check requestType").isEqualTo(expected.getRequestType()))
            .satisfies(a -> assertThat(a.getTestType()).as("check testType").isEqualTo(expected.getTestType()))
            .satisfies(a -> assertThat(a.getApiUrl()).as("check apiUrl").isEqualTo(expected.getApiUrl()))
            .satisfies(a -> assertThat(a.getDataFormat()).as("check dataFormat").isEqualTo(expected.getDataFormat()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiRequestLogUpdatableRelationshipsEquals(ApiRequestLog expected, ApiRequestLog actual) {
        // empty method
    }
}
