package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssayAllPropertiesEquals(Assay expected, Assay actual) {
        assertAssayAutoGeneratedPropertiesEquals(expected, actual);
        assertAssayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssayAllUpdatablePropertiesEquals(Assay expected, Assay actual) {
        assertAssayUpdatableFieldsEquals(expected, actual);
        assertAssayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssayAutoGeneratedPropertiesEquals(Assay expected, Assay actual) {
        assertThat(actual)
            .as("Verify Assay auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssayUpdatableFieldsEquals(Assay expected, Assay actual) {
        assertThat(actual)
            .as("Verify Assay relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAssayType()).as("check assayType").isEqualTo(expected.getAssayType()))
            .satisfies(a -> assertThat(a.getManufacturer()).as("check manufacturer").isEqualTo(expected.getManufacturer()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssayUpdatableRelationshipsEquals(Assay expected, Assay actual) {
        assertThat(actual)
            .as("Verify Assay relationships")
            .satisfies(a -> assertThat(a.getScheme()).as("check scheme").isEqualTo(expected.getScheme()));
    }
}
