package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CapaRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapaRecordAllPropertiesEquals(CapaRecord expected, CapaRecord actual) {
        assertCapaRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertCapaRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapaRecordAllUpdatablePropertiesEquals(CapaRecord expected, CapaRecord actual) {
        assertCapaRecordUpdatableFieldsEquals(expected, actual);
        assertCapaRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapaRecordAutoGeneratedPropertiesEquals(CapaRecord expected, CapaRecord actual) {
        assertThat(actual)
            .as("Verify CapaRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapaRecordUpdatableFieldsEquals(CapaRecord expected, CapaRecord actual) {
        assertThat(actual)
            .as("Verify CapaRecord relevant properties")
            .satisfies(a -> assertThat(a.getRootCause()).as("check rootCause").isEqualTo(expected.getRootCause()))
            .satisfies(a -> assertThat(a.getActionTaken()).as("check actionTaken").isEqualTo(expected.getActionTaken()))
            .satisfies(a -> assertThat(a.getActionDate()).as("check actionDate").isEqualTo(expected.getActionDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getFollowUpDate()).as("check followUpDate").isEqualTo(expected.getFollowUpDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapaRecordUpdatableRelationshipsEquals(CapaRecord expected, CapaRecord actual) {
        assertThat(actual)
            .as("Verify CapaRecord relationships")
            .satisfies(a -> assertThat(a.getCorrectiveAction()).as("check correctiveAction").isEqualTo(expected.getCorrectiveAction()))
            .satisfies(a ->
                assertThat(a.getShipmentParticipantMap()).as("check shipmentParticipantMap").isEqualTo(expected.getShipmentParticipantMap())
            );
    }
}
