package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CertificateBatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateBatchAllPropertiesEquals(CertificateBatch expected, CertificateBatch actual) {
        assertCertificateBatchAutoGeneratedPropertiesEquals(expected, actual);
        assertCertificateBatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateBatchAllUpdatablePropertiesEquals(CertificateBatch expected, CertificateBatch actual) {
        assertCertificateBatchUpdatableFieldsEquals(expected, actual);
        assertCertificateBatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateBatchAutoGeneratedPropertiesEquals(CertificateBatch expected, CertificateBatch actual) {
        assertThat(actual)
            .as("Verify CertificateBatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateBatchUpdatableFieldsEquals(CertificateBatch expected, CertificateBatch actual) {
        assertThat(actual)
            .as("Verify CertificateBatch relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getExcellenceCount()).as("check excellenceCount").isEqualTo(expected.getExcellenceCount()))
            .satisfies(a ->
                assertThat(a.getParticipationCount()).as("check participationCount").isEqualTo(expected.getParticipationCount())
            )
            .satisfies(a -> assertThat(a.getSkippedCount()).as("check skippedCount").isEqualTo(expected.getSkippedCount()))
            .satisfies(a -> assertThat(a.getDownloadUrl()).as("check downloadUrl").isEqualTo(expected.getDownloadUrl()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getApprovedBy()).as("check approvedBy").isEqualTo(expected.getApprovedBy()))
            .satisfies(a -> assertThat(a.getApprovedOn()).as("check approvedOn").isEqualTo(expected.getApprovedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateBatchUpdatableRelationshipsEquals(CertificateBatch expected, CertificateBatch actual) {
        assertThat(actual)
            .as("Verify CertificateBatch relationships")
            .satisfies(a -> assertThat(a.getShipmentses()).as("check shipmentses").isEqualTo(expected.getShipmentses()));
    }
}
