package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CertificateTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateTemplateAllPropertiesEquals(CertificateTemplate expected, CertificateTemplate actual) {
        assertCertificateTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertCertificateTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateTemplateAllUpdatablePropertiesEquals(CertificateTemplate expected, CertificateTemplate actual) {
        assertCertificateTemplateUpdatableFieldsEquals(expected, actual);
        assertCertificateTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateTemplateAutoGeneratedPropertiesEquals(CertificateTemplate expected, CertificateTemplate actual) {
        assertThat(actual)
            .as("Verify CertificateTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateTemplateUpdatableFieldsEquals(CertificateTemplate expected, CertificateTemplate actual) {
        assertThat(actual)
            .as("Verify CertificateTemplate relevant properties")
            .satisfies(a -> assertThat(a.getCertificateType()).as("check certificateType").isEqualTo(expected.getCertificateType()))
            .satisfies(a -> assertThat(a.getFileRef()).as("check fileRef").isEqualTo(expected.getFileRef()))
            .satisfies(a -> assertThat(a.getDetectedFields()).as("check detectedFields").isEqualTo(expected.getDetectedFields()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCertificateTemplateUpdatableRelationshipsEquals(CertificateTemplate expected, CertificateTemplate actual) {
        // empty method
    }
}
