package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContactMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactMessageAllPropertiesEquals(ContactMessage expected, ContactMessage actual) {
        assertContactMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertContactMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactMessageAllUpdatablePropertiesEquals(ContactMessage expected, ContactMessage actual) {
        assertContactMessageUpdatableFieldsEquals(expected, actual);
        assertContactMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactMessageAutoGeneratedPropertiesEquals(ContactMessage expected, ContactMessage actual) {
        assertThat(actual)
            .as("Verify ContactMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactMessageUpdatableFieldsEquals(ContactMessage expected, ContactMessage actual) {
        assertThat(actual)
            .as("Verify ContactMessage relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getSubmittedAt()).as("check submittedAt").isEqualTo(expected.getSubmittedAt()))
            .satisfies(a -> assertThat(a.getIsHandled()).as("check isHandled").isEqualTo(expected.getIsHandled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactMessageUpdatableRelationshipsEquals(ContactMessage expected, ContactMessage actual) {
        // empty method
    }
}
