package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CorrectiveActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrectiveActionAllPropertiesEquals(CorrectiveAction expected, CorrectiveAction actual) {
        assertCorrectiveActionAutoGeneratedPropertiesEquals(expected, actual);
        assertCorrectiveActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrectiveActionAllUpdatablePropertiesEquals(CorrectiveAction expected, CorrectiveAction actual) {
        assertCorrectiveActionUpdatableFieldsEquals(expected, actual);
        assertCorrectiveActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrectiveActionAutoGeneratedPropertiesEquals(CorrectiveAction expected, CorrectiveAction actual) {
        assertThat(actual)
            .as("Verify CorrectiveAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrectiveActionUpdatableFieldsEquals(CorrectiveAction expected, CorrectiveAction actual) {
        assertThat(actual)
            .as("Verify CorrectiveAction relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrectiveActionUpdatableRelationshipsEquals(CorrectiveAction expected, CorrectiveAction actual) {
        assertThat(actual)
            .as("Verify CorrectiveAction relationships")
            .satisfies(a -> assertThat(a.getScheme()).as("check scheme").isEqualTo(expected.getScheme()));
    }
}
