package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomFieldDefinitionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomFieldDefinitionAllPropertiesEquals(CustomFieldDefinition expected, CustomFieldDefinition actual) {
        assertCustomFieldDefinitionAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomFieldDefinitionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomFieldDefinitionAllUpdatablePropertiesEquals(
        CustomFieldDefinition expected,
        CustomFieldDefinition actual
    ) {
        assertCustomFieldDefinitionUpdatableFieldsEquals(expected, actual);
        assertCustomFieldDefinitionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomFieldDefinitionAutoGeneratedPropertiesEquals(
        CustomFieldDefinition expected,
        CustomFieldDefinition actual
    ) {
        assertThat(actual)
            .as("Verify CustomFieldDefinition auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomFieldDefinitionUpdatableFieldsEquals(CustomFieldDefinition expected, CustomFieldDefinition actual) {
        assertThat(actual)
            .as("Verify CustomFieldDefinition relevant properties")
            .satisfies(a -> assertThat(a.getFieldKey()).as("check fieldKey").isEqualTo(expected.getFieldKey()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getFieldType()).as("check fieldType").isEqualTo(expected.getFieldType()))
            .satisfies(a -> assertThat(a.getOptions()).as("check options").isEqualTo(expected.getOptions()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomFieldDefinitionUpdatableRelationshipsEquals(
        CustomFieldDefinition expected,
        CustomFieldDefinition actual
    ) {
        // empty method
    }
}
