package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DataManagerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataManagerAllPropertiesEquals(DataManager expected, DataManager actual) {
        assertDataManagerAutoGeneratedPropertiesEquals(expected, actual);
        assertDataManagerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataManagerAllUpdatablePropertiesEquals(DataManager expected, DataManager actual) {
        assertDataManagerUpdatableFieldsEquals(expected, actual);
        assertDataManagerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataManagerAutoGeneratedPropertiesEquals(DataManager expected, DataManager actual) {
        assertThat(actual)
            .as("Verify DataManager auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataManagerUpdatableFieldsEquals(DataManager expected, DataManager actual) {
        assertThat(actual)
            .as("Verify DataManager relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getInstitute()).as("check institute").isEqualTo(expected.getInstitute()))
            .satisfies(a -> assertThat(a.getPrimaryEmail()).as("check primaryEmail").isEqualTo(expected.getPrimaryEmail()))
            .satisfies(a -> assertThat(a.getSecondaryEmail()).as("check secondaryEmail").isEqualTo(expected.getSecondaryEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getMobile()).as("check mobile").isEqualTo(expected.getMobile()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getQcAccess()).as("check qcAccess").isEqualTo(expected.getQcAccess()))
            .satisfies(a -> assertThat(a.getViewOnlyAccess()).as("check viewOnlyAccess").isEqualTo(expected.getViewOnlyAccess()))
            .satisfies(a ->
                assertThat(a.getEnableTestResponseDate()).as("check enableTestResponseDate").isEqualTo(expected.getEnableTestResponseDate())
            )
            .satisfies(a ->
                assertThat(a.getEnableModeOfReceipt()).as("check enableModeOfReceipt").isEqualTo(expected.getEnableModeOfReceipt())
            )
            .satisfies(a -> assertThat(a.getForceProfileCheck()).as("check forceProfileCheck").isEqualTo(expected.getForceProfileCheck()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataManagerUpdatableRelationshipsEquals(DataManager expected, DataManager actual) {
        assertThat(actual)
            .as("Verify DataManager relationships")
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getParticipantses()).as("check participantses").isEqualTo(expected.getParticipantses()));
    }
}
