package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DistributionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributionAllPropertiesEquals(Distribution expected, Distribution actual) {
        assertDistributionAutoGeneratedPropertiesEquals(expected, actual);
        assertDistributionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributionAllUpdatablePropertiesEquals(Distribution expected, Distribution actual) {
        assertDistributionUpdatableFieldsEquals(expected, actual);
        assertDistributionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributionAutoGeneratedPropertiesEquals(Distribution expected, Distribution actual) {
        assertThat(actual)
            .as("Verify Distribution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributionUpdatableFieldsEquals(Distribution expected, Distribution actual) {
        assertThat(actual)
            .as("Verify Distribution relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDistributionDate()).as("check distributionDate").isEqualTo(expected.getDistributionDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributionUpdatableRelationshipsEquals(Distribution expected, Distribution actual) {
        // empty method
    }
}
