package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailMessageAllPropertiesEquals(EmailMessage expected, EmailMessage actual) {
        assertEmailMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailMessageAllUpdatablePropertiesEquals(EmailMessage expected, EmailMessage actual) {
        assertEmailMessageUpdatableFieldsEquals(expected, actual);
        assertEmailMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailMessageAutoGeneratedPropertiesEquals(EmailMessage expected, EmailMessage actual) {
        assertThat(actual)
            .as("Verify EmailMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailMessageUpdatableFieldsEquals(EmailMessage expected, EmailMessage actual) {
        assertThat(actual)
            .as("Verify EmailMessage relevant properties")
            .satisfies(a -> assertThat(a.getFromEmail()).as("check fromEmail").isEqualTo(expected.getFromEmail()))
            .satisfies(a -> assertThat(a.getFromName()).as("check fromName").isEqualTo(expected.getFromName()))
            .satisfies(a -> assertThat(a.getReplyTo()).as("check replyTo").isEqualTo(expected.getReplyTo()))
            .satisfies(a -> assertThat(a.getToEmail()).as("check toEmail").isEqualTo(expected.getToEmail()))
            .satisfies(a -> assertThat(a.getCc()).as("check cc").isEqualTo(expected.getCc()))
            .satisfies(a -> assertThat(a.getBcc()).as("check bcc").isEqualTo(expected.getBcc()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getAttachmentRef()).as("check attachmentRef").isEqualTo(expected.getAttachmentRef()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getFailureType()).as("check failureType").isEqualTo(expected.getFailureType()))
            .satisfies(a -> assertThat(a.getFailureReason()).as("check failureReason").isEqualTo(expected.getFailureReason()))
            .satisfies(a -> assertThat(a.getQueuedOn()).as("check queuedOn").isEqualTo(expected.getQueuedOn()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()))
            .satisfies(a -> assertThat(a.getRetryCount()).as("check retryCount").isEqualTo(expected.getRetryCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailMessageUpdatableRelationshipsEquals(EmailMessage expected, EmailMessage actual) {
        assertThat(actual)
            .as("Verify EmailMessage relationships")
            .satisfies(a -> assertThat(a.getTemplate()).as("check template").isEqualTo(expected.getTemplate()));
    }
}
