package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnrollmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnrollmentAllPropertiesEquals(Enrollment expected, Enrollment actual) {
        assertEnrollmentAutoGeneratedPropertiesEquals(expected, actual);
        assertEnrollmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnrollmentAllUpdatablePropertiesEquals(Enrollment expected, Enrollment actual) {
        assertEnrollmentUpdatableFieldsEquals(expected, actual);
        assertEnrollmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnrollmentAutoGeneratedPropertiesEquals(Enrollment expected, Enrollment actual) {
        assertThat(actual)
            .as("Verify Enrollment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnrollmentUpdatableFieldsEquals(Enrollment expected, Enrollment actual) {
        assertThat(actual)
            .as("Verify Enrollment relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getEnrolledOn()).as("check enrolledOn").isEqualTo(expected.getEnrolledOn()))
            .satisfies(a -> assertThat(a.getWithdrawnOn()).as("check withdrawnOn").isEqualTo(expected.getWithdrawnOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnrollmentUpdatableRelationshipsEquals(Enrollment expected, Enrollment actual) {
        assertThat(actual)
            .as("Verify Enrollment relationships")
            .satisfies(a -> assertThat(a.getParticipant()).as("check participant").isEqualTo(expected.getParticipant()))
            .satisfies(a -> assertThat(a.getScheme()).as("check scheme").isEqualTo(expected.getScheme()));
    }
}
