package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedbackQuestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackQuestionAllPropertiesEquals(FeedbackQuestion expected, FeedbackQuestion actual) {
        assertFeedbackQuestionAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedbackQuestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackQuestionAllUpdatablePropertiesEquals(FeedbackQuestion expected, FeedbackQuestion actual) {
        assertFeedbackQuestionUpdatableFieldsEquals(expected, actual);
        assertFeedbackQuestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackQuestionAutoGeneratedPropertiesEquals(FeedbackQuestion expected, FeedbackQuestion actual) {
        assertThat(actual)
            .as("Verify FeedbackQuestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackQuestionUpdatableFieldsEquals(FeedbackQuestion expected, FeedbackQuestion actual) {
        assertThat(actual)
            .as("Verify FeedbackQuestion relevant properties")
            .satisfies(a -> assertThat(a.getQuestionText()).as("check questionText").isEqualTo(expected.getQuestionText()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackQuestionUpdatableRelationshipsEquals(FeedbackQuestion expected, FeedbackQuestion actual) {
        // empty method
    }
}
