package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GlobalConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationAllPropertiesEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertGlobalConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertGlobalConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationAllUpdatablePropertiesEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertGlobalConfigurationUpdatableFieldsEquals(expected, actual);
        assertGlobalConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationAutoGeneratedPropertiesEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertThat(actual)
            .as("Verify GlobalConfiguration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationUpdatableFieldsEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertThat(actual)
            .as("Verify GlobalConfiguration relevant properties")
            .satisfies(a -> assertThat(a.getConfigKey()).as("check configKey").isEqualTo(expected.getConfigKey()))
            .satisfies(a -> assertThat(a.getConfigValue()).as("check configValue").isEqualTo(expected.getConfigValue()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationUpdatableRelationshipsEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        // empty method
    }
}
