package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HomePageSectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHomePageSectionAllPropertiesEquals(HomePageSection expected, HomePageSection actual) {
        assertHomePageSectionAutoGeneratedPropertiesEquals(expected, actual);
        assertHomePageSectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHomePageSectionAllUpdatablePropertiesEquals(HomePageSection expected, HomePageSection actual) {
        assertHomePageSectionUpdatableFieldsEquals(expected, actual);
        assertHomePageSectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHomePageSectionAutoGeneratedPropertiesEquals(HomePageSection expected, HomePageSection actual) {
        assertThat(actual)
            .as("Verify HomePageSection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHomePageSectionUpdatableFieldsEquals(HomePageSection expected, HomePageSection actual) {
        assertThat(actual)
            .as("Verify HomePageSection relevant properties")
            .satisfies(a -> assertThat(a.getSection()).as("check section").isEqualTo(expected.getSection()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()))
            .satisfies(a -> assertThat(a.getLink()).as("check link").isEqualTo(expected.getLink()))
            .satisfies(a -> assertThat(a.getFileRef()).as("check fileRef").isEqualTo(expected.getFileRef()))
            .satisfies(a -> assertThat(a.getIcon()).as("check icon").isEqualTo(expected.getIcon()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHomePageSectionUpdatableRelationshipsEquals(HomePageSection expected, HomePageSection actual) {
        // empty method
    }
}
