package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MailTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMailTemplateAllPropertiesEquals(MailTemplate expected, MailTemplate actual) {
        assertMailTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertMailTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMailTemplateAllUpdatablePropertiesEquals(MailTemplate expected, MailTemplate actual) {
        assertMailTemplateUpdatableFieldsEquals(expected, actual);
        assertMailTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMailTemplateAutoGeneratedPropertiesEquals(MailTemplate expected, MailTemplate actual) {
        assertThat(actual)
            .as("Verify MailTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMailTemplateUpdatableFieldsEquals(MailTemplate expected, MailTemplate actual) {
        assertThat(actual)
            .as("Verify MailTemplate relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getHtmlBody()).as("check htmlBody").isEqualTo(expected.getHtmlBody()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMailTemplateUpdatableRelationshipsEquals(MailTemplate expected, MailTemplate actual) {
        // empty method
    }
}
