package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModeOfReceiptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeOfReceiptAllPropertiesEquals(ModeOfReceipt expected, ModeOfReceipt actual) {
        assertModeOfReceiptAutoGeneratedPropertiesEquals(expected, actual);
        assertModeOfReceiptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeOfReceiptAllUpdatablePropertiesEquals(ModeOfReceipt expected, ModeOfReceipt actual) {
        assertModeOfReceiptUpdatableFieldsEquals(expected, actual);
        assertModeOfReceiptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeOfReceiptAutoGeneratedPropertiesEquals(ModeOfReceipt expected, ModeOfReceipt actual) {
        assertThat(actual)
            .as("Verify ModeOfReceipt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeOfReceiptUpdatableFieldsEquals(ModeOfReceipt expected, ModeOfReceipt actual) {
        assertThat(actual)
            .as("Verify ModeOfReceipt relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeOfReceiptUpdatableRelationshipsEquals(ModeOfReceipt expected, ModeOfReceipt actual) {
        // empty method
    }
}
