package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotTestedReasonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotTestedReasonAllPropertiesEquals(NotTestedReason expected, NotTestedReason actual) {
        assertNotTestedReasonAutoGeneratedPropertiesEquals(expected, actual);
        assertNotTestedReasonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotTestedReasonAllUpdatablePropertiesEquals(NotTestedReason expected, NotTestedReason actual) {
        assertNotTestedReasonUpdatableFieldsEquals(expected, actual);
        assertNotTestedReasonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotTestedReasonAutoGeneratedPropertiesEquals(NotTestedReason expected, NotTestedReason actual) {
        assertThat(actual)
            .as("Verify NotTestedReason auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotTestedReasonUpdatableFieldsEquals(NotTestedReason expected, NotTestedReason actual) {
        assertThat(actual)
            .as("Verify NotTestedReason relevant properties")
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotTestedReasonUpdatableRelationshipsEquals(NotTestedReason expected, NotTestedReason actual) {
        // empty method
    }
}
