package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParticipantMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantMessageAllPropertiesEquals(ParticipantMessage expected, ParticipantMessage actual) {
        assertParticipantMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertParticipantMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantMessageAllUpdatablePropertiesEquals(ParticipantMessage expected, ParticipantMessage actual) {
        assertParticipantMessageUpdatableFieldsEquals(expected, actual);
        assertParticipantMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantMessageAutoGeneratedPropertiesEquals(ParticipantMessage expected, ParticipantMessage actual) {
        assertThat(actual)
            .as("Verify ParticipantMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantMessageUpdatableFieldsEquals(ParticipantMessage expected, ParticipantMessage actual) {
        assertThat(actual)
            .as("Verify ParticipantMessage relevant properties")
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getIsRead()).as("check isRead").isEqualTo(expected.getIsRead()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantMessageUpdatableRelationshipsEquals(ParticipantMessage expected, ParticipantMessage actual) {
        assertThat(actual)
            .as("Verify ParticipantMessage relationships")
            .satisfies(a -> assertThat(a.getParticipant()).as("check participant").isEqualTo(expected.getParticipant()));
    }
}
