package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParticipantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantAllPropertiesEquals(Participant expected, Participant actual) {
        assertParticipantAutoGeneratedPropertiesEquals(expected, actual);
        assertParticipantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantAllUpdatablePropertiesEquals(Participant expected, Participant actual) {
        assertParticipantUpdatableFieldsEquals(expected, actual);
        assertParticipantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantAutoGeneratedPropertiesEquals(Participant expected, Participant actual) {
        assertThat(actual)
            .as("Verify Participant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantUpdatableFieldsEquals(Participant expected, Participant actual) {
        assertThat(actual)
            .as("Verify Participant relevant properties")
            .satisfies(a -> assertThat(a.getUniqueIdentifier()).as("check uniqueIdentifier").isEqualTo(expected.getUniqueIdentifier()))
            .satisfies(a -> assertThat(a.getInstituteName()).as("check instituteName").isEqualTo(expected.getInstituteName()))
            .satisfies(a -> assertThat(a.getDepartmentName()).as("check departmentName").isEqualTo(expected.getDepartmentName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getAdditionalEmail()).as("check additionalEmail").isEqualTo(expected.getAdditionalEmail()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getShippingAddress()).as("check shippingAddress").isEqualTo(expected.getShippingAddress()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()))
            .satisfies(a -> assertThat(a.getDistrict()).as("check district").isEqualTo(expected.getDistrict()))
            .satisfies(a -> assertThat(a.getZip()).as("check zip").isEqualTo(expected.getZip()))
            .satisfies(a -> assertThat(a.getRegion()).as("check region").isEqualTo(expected.getRegion()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getMobile()).as("check mobile").isEqualTo(expected.getMobile()))
            .satisfies(a -> assertThat(a.getAffiliation()).as("check affiliation").isEqualTo(expected.getAffiliation()))
            .satisfies(a -> assertThat(a.getNetworkTier()).as("check networkTier").isEqualTo(expected.getNetworkTier()))
            .satisfies(a -> assertThat(a.getSiteType()).as("check siteType").isEqualTo(expected.getSiteType()))
            .satisfies(a -> assertThat(a.getFundingSource()).as("check fundingSource").isEqualTo(expected.getFundingSource()))
            .satisfies(a -> assertThat(a.getTestingVolume()).as("check testingVolume").isEqualTo(expected.getTestingVolume()))
            .satisfies(a -> assertThat(a.getPepfarId()).as("check pepfarId").isEqualTo(expected.getPepfarId()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getLabDirectorName()).as("check labDirectorName").isEqualTo(expected.getLabDirectorName()))
            .satisfies(a -> assertThat(a.getLabDirectorEmail()).as("check labDirectorEmail").isEqualTo(expected.getLabDirectorEmail()))
            .satisfies(a -> assertThat(a.getContactPersonName()).as("check contactPersonName").isEqualTo(expected.getContactPersonName()))
            .satisfies(a ->
                assertThat(a.getContactPersonEmail()).as("check contactPersonEmail").isEqualTo(expected.getContactPersonEmail())
            )
            .satisfies(a ->
                assertThat(a.getContactPersonPhone()).as("check contactPersonPhone").isEqualTo(expected.getContactPersonPhone())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantUpdatableRelationshipsEquals(Participant expected, Participant actual) {
        assertThat(actual)
            .as("Verify Participant relationships")
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getDataManagerses()).as("check dataManagerses").isEqualTo(expected.getDataManagerses()));
    }
}
