package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParticipantFeedbackAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantFeedbackAllPropertiesEquals(ParticipantFeedback expected, ParticipantFeedback actual) {
        assertParticipantFeedbackAutoGeneratedPropertiesEquals(expected, actual);
        assertParticipantFeedbackAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantFeedbackAllUpdatablePropertiesEquals(ParticipantFeedback expected, ParticipantFeedback actual) {
        assertParticipantFeedbackUpdatableFieldsEquals(expected, actual);
        assertParticipantFeedbackUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantFeedbackAutoGeneratedPropertiesEquals(ParticipantFeedback expected, ParticipantFeedback actual) {
        assertThat(actual)
            .as("Verify ParticipantFeedback auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantFeedbackUpdatableFieldsEquals(ParticipantFeedback expected, ParticipantFeedback actual) {
        assertThat(actual)
            .as("Verify ParticipantFeedback relevant properties")
            .satisfies(a -> assertThat(a.getAnswer()).as("check answer").isEqualTo(expected.getAnswer()))
            .satisfies(a -> assertThat(a.getSubmittedAt()).as("check submittedAt").isEqualTo(expected.getSubmittedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantFeedbackUpdatableRelationshipsEquals(ParticipantFeedback expected, ParticipantFeedback actual) {
        assertThat(actual)
            .as("Verify ParticipantFeedback relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getParticipant()).as("check participant").isEqualTo(expected.getParticipant()))
            .satisfies(a -> assertThat(a.getShipment()).as("check shipment").isEqualTo(expected.getShipment()));
    }
}
