package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParticipantResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantResultAllPropertiesEquals(ParticipantResult expected, ParticipantResult actual) {
        assertParticipantResultAutoGeneratedPropertiesEquals(expected, actual);
        assertParticipantResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantResultAllUpdatablePropertiesEquals(ParticipantResult expected, ParticipantResult actual) {
        assertParticipantResultUpdatableFieldsEquals(expected, actual);
        assertParticipantResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantResultAutoGeneratedPropertiesEquals(ParticipantResult expected, ParticipantResult actual) {
        assertThat(actual)
            .as("Verify ParticipantResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantResultUpdatableFieldsEquals(ParticipantResult expected, ParticipantResult actual) {
        assertThat(actual)
            .as("Verify ParticipantResult relevant properties")
            .satisfies(a ->
                assertThat(a.getReportedQualitativeResult())
                    .as("check reportedQualitativeResult")
                    .isEqualTo(expected.getReportedQualitativeResult())
            )
            .satisfies(a ->
                assertThat(a.getReportedQuantitativeValue())
                    .as("check reportedQuantitativeValue")
                    .isEqualTo(expected.getReportedQuantitativeValue())
            )
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getLotNumber()).as("check lotNumber").isEqualTo(expected.getLotNumber()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getzScore()).as("check zScore").isEqualTo(expected.getzScore()))
            .satisfies(a -> assertThat(a.getCalculatedScore()).as("check calculatedScore").isEqualTo(expected.getCalculatedScore()))
            .satisfies(a -> assertThat(a.getComments()).as("check comments").isEqualTo(expected.getComments()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantResultUpdatableRelationshipsEquals(ParticipantResult expected, ParticipantResult actual) {
        assertThat(actual)
            .as("Verify ParticipantResult relationships")
            .satisfies(a -> assertThat(a.getAssay()).as("check assay").isEqualTo(expected.getAssay()))
            .satisfies(a -> assertThat(a.getTestKit()).as("check testKit").isEqualTo(expected.getTestKit()))
            .satisfies(a -> assertThat(a.getSample()).as("check sample").isEqualTo(expected.getSample()))
            .satisfies(a ->
                assertThat(a.getShipmentParticipantMap()).as("check shipmentParticipantMap").isEqualTo(expected.getShipmentParticipantMap())
            );
    }
}
