package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParticipantCustomValueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantCustomValueAllPropertiesEquals(ParticipantCustomValue expected, ParticipantCustomValue actual) {
        assertParticipantCustomValueAutoGeneratedPropertiesEquals(expected, actual);
        assertParticipantCustomValueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantCustomValueAllUpdatablePropertiesEquals(
        ParticipantCustomValue expected,
        ParticipantCustomValue actual
    ) {
        assertParticipantCustomValueUpdatableFieldsEquals(expected, actual);
        assertParticipantCustomValueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantCustomValueAutoGeneratedPropertiesEquals(
        ParticipantCustomValue expected,
        ParticipantCustomValue actual
    ) {
        assertThat(actual)
            .as("Verify ParticipantCustomValue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantCustomValueUpdatableFieldsEquals(ParticipantCustomValue expected, ParticipantCustomValue actual) {
        assertThat(actual)
            .as("Verify ParticipantCustomValue relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantCustomValueUpdatableRelationshipsEquals(
        ParticipantCustomValue expected,
        ParticipantCustomValue actual
    ) {
        assertThat(actual)
            .as("Verify ParticipantCustomValue relationships")
            .satisfies(a -> assertThat(a.getParticipant()).as("check participant").isEqualTo(expected.getParticipant()))
            .satisfies(a -> assertThat(a.getDefinition()).as("check definition").isEqualTo(expected.getDefinition()));
    }
}
