package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportConfigurationAllPropertiesEquals(ReportConfiguration expected, ReportConfiguration actual) {
        assertReportConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertReportConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportConfigurationAllUpdatablePropertiesEquals(ReportConfiguration expected, ReportConfiguration actual) {
        assertReportConfigurationUpdatableFieldsEquals(expected, actual);
        assertReportConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportConfigurationAutoGeneratedPropertiesEquals(ReportConfiguration expected, ReportConfiguration actual) {
        assertThat(actual)
            .as("Verify ReportConfiguration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportConfigurationUpdatableFieldsEquals(ReportConfiguration expected, ReportConfiguration actual) {
        assertThat(actual)
            .as("Verify ReportConfiguration relevant properties")
            .satisfies(a -> assertThat(a.getReportHeader()).as("check reportHeader").isEqualTo(expected.getReportHeader()))
            .satisfies(a -> assertThat(a.getLogo()).as("check logo").isEqualTo(expected.getLogo()))
            .satisfies(a -> assertThat(a.getLogoRight()).as("check logoRight").isEqualTo(expected.getLogoRight()))
            .satisfies(a -> assertThat(a.getLayout()).as("check layout").isEqualTo(expected.getLayout()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getTopMargin()).as("check topMargin").isEqualTo(expected.getTopMargin()))
            .satisfies(a ->
                assertThat(a.getInstituteAddressPosition())
                    .as("check instituteAddressPosition")
                    .isEqualTo(expected.getInstituteAddressPosition())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportConfigurationUpdatableRelationshipsEquals(ReportConfiguration expected, ReportConfiguration actual) {
        assertThat(actual)
            .as("Verify ReportConfiguration relationships")
            .satisfies(a -> assertThat(a.getScheme()).as("check scheme").isEqualTo(expected.getScheme()));
    }
}
