package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SampleReferenceResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSampleReferenceResultAllPropertiesEquals(SampleReferenceResult expected, SampleReferenceResult actual) {
        assertSampleReferenceResultAutoGeneratedPropertiesEquals(expected, actual);
        assertSampleReferenceResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSampleReferenceResultAllUpdatablePropertiesEquals(
        SampleReferenceResult expected,
        SampleReferenceResult actual
    ) {
        assertSampleReferenceResultUpdatableFieldsEquals(expected, actual);
        assertSampleReferenceResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSampleReferenceResultAutoGeneratedPropertiesEquals(
        SampleReferenceResult expected,
        SampleReferenceResult actual
    ) {
        assertThat(actual)
            .as("Verify SampleReferenceResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSampleReferenceResultUpdatableFieldsEquals(SampleReferenceResult expected, SampleReferenceResult actual) {
        assertThat(actual)
            .as("Verify SampleReferenceResult relevant properties")
            .satisfies(a -> assertThat(a.getQualitativeResult()).as("check qualitativeResult").isEqualTo(expected.getQualitativeResult()))
            .satisfies(a -> assertThat(a.getQuantitativeValue()).as("check quantitativeValue").isEqualTo(expected.getQuantitativeValue()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getLowerLimit()).as("check lowerLimit").isEqualTo(expected.getLowerLimit()))
            .satisfies(a -> assertThat(a.getUpperLimit()).as("check upperLimit").isEqualTo(expected.getUpperLimit()))
            .satisfies(a -> assertThat(a.getIsControlExpected()).as("check isControlExpected").isEqualTo(expected.getIsControlExpected()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSampleReferenceResultUpdatableRelationshipsEquals(
        SampleReferenceResult expected,
        SampleReferenceResult actual
    ) {
        assertThat(actual)
            .as("Verify SampleReferenceResult relationships")
            .satisfies(a -> assertThat(a.getAssay()).as("check assay").isEqualTo(expected.getAssay()))
            .satisfies(a -> assertThat(a.getSample()).as("check sample").isEqualTo(expected.getSample()));
    }
}
