package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SchemeConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeConfigurationAllPropertiesEquals(SchemeConfiguration expected, SchemeConfiguration actual) {
        assertSchemeConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertSchemeConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeConfigurationAllUpdatablePropertiesEquals(SchemeConfiguration expected, SchemeConfiguration actual) {
        assertSchemeConfigurationUpdatableFieldsEquals(expected, actual);
        assertSchemeConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeConfigurationAutoGeneratedPropertiesEquals(SchemeConfiguration expected, SchemeConfiguration actual) {
        assertThat(actual)
            .as("Verify SchemeConfiguration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeConfigurationUpdatableFieldsEquals(SchemeConfiguration expected, SchemeConfiguration actual) {
        assertThat(actual)
            .as("Verify SchemeConfiguration relevant properties")
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getEffectiveDate()).as("check effectiveDate").isEqualTo(expected.getEffectiveDate()))
            .satisfies(a -> assertThat(a.getPassingScore()).as("check passingScore").isEqualTo(expected.getPassingScore()))
            .satisfies(a ->
                assertThat(a.getDocumentationWeight()).as("check documentationWeight").isEqualTo(expected.getDocumentationWeight())
            )
            .satisfies(a -> assertThat(a.getAllowLateResponse()).as("check allowLateResponse").isEqualTo(expected.getAllowLateResponse()))
            .satisfies(a -> assertThat(a.getOptionalFields()).as("check optionalFields").isEqualTo(expected.getOptionalFields()))
            .satisfies(a -> assertThat(a.getScoringRules()).as("check scoringRules").isEqualTo(expected.getScoringRules()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeConfigurationUpdatableRelationshipsEquals(SchemeConfiguration expected, SchemeConfiguration actual) {
        assertThat(actual)
            .as("Verify SchemeConfiguration relationships")
            .satisfies(a -> assertThat(a.getScheme()).as("check scheme").isEqualTo(expected.getScheme()));
    }
}
