package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScheduledJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduledJobAllPropertiesEquals(ScheduledJob expected, ScheduledJob actual) {
        assertScheduledJobAutoGeneratedPropertiesEquals(expected, actual);
        assertScheduledJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduledJobAllUpdatablePropertiesEquals(ScheduledJob expected, ScheduledJob actual) {
        assertScheduledJobUpdatableFieldsEquals(expected, actual);
        assertScheduledJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduledJobAutoGeneratedPropertiesEquals(ScheduledJob expected, ScheduledJob actual) {
        assertThat(actual)
            .as("Verify ScheduledJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduledJobUpdatableFieldsEquals(ScheduledJob expected, ScheduledJob actual) {
        assertThat(actual)
            .as("Verify ScheduledJob relevant properties")
            .satisfies(a -> assertThat(a.getJobType()).as("check jobType").isEqualTo(expected.getJobType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRequestedBy()).as("check requestedBy").isEqualTo(expected.getRequestedBy()))
            .satisfies(a -> assertThat(a.getRequestedOn()).as("check requestedOn").isEqualTo(expected.getRequestedOn()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getLastHeartbeat()).as("check lastHeartbeat").isEqualTo(expected.getLastHeartbeat()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getProgressCompleted()).as("check progressCompleted").isEqualTo(expected.getProgressCompleted()))
            .satisfies(a -> assertThat(a.getProgressTotal()).as("check progressTotal").isEqualTo(expected.getProgressTotal()))
            .satisfies(a -> assertThat(a.getSummary()).as("check summary").isEqualTo(expected.getSummary()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduledJobUpdatableRelationshipsEquals(ScheduledJob expected, ScheduledJob actual) {
        // empty method
    }
}
