package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SchemeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeAllPropertiesEquals(Scheme expected, Scheme actual) {
        assertSchemeAutoGeneratedPropertiesEquals(expected, actual);
        assertSchemeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeAllUpdatablePropertiesEquals(Scheme expected, Scheme actual) {
        assertSchemeUpdatableFieldsEquals(expected, actual);
        assertSchemeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeAutoGeneratedPropertiesEquals(Scheme expected, Scheme actual) {
        assertThat(actual)
            .as("Verify Scheme auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeUpdatableFieldsEquals(Scheme expected, Scheme actual) {
        assertThat(actual)
            .as("Verify Scheme relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSchemeType()).as("check schemeType").isEqualTo(expected.getSchemeType()))
            .satisfies(a -> assertThat(a.getModality()).as("check modality").isEqualTo(expected.getModality()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSchemeUpdatableRelationshipsEquals(Scheme expected, Scheme actual) {
        assertThat(actual)
            .as("Verify Scheme relationships")
            .satisfies(a ->
                assertThat(a.getCertificateTemplate()).as("check certificateTemplate").isEqualTo(expected.getCertificateTemplate())
            );
    }
}
