package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentParticipantMapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentParticipantMapAllPropertiesEquals(ShipmentParticipantMap expected, ShipmentParticipantMap actual) {
        assertShipmentParticipantMapAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentParticipantMapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentParticipantMapAllUpdatablePropertiesEquals(
        ShipmentParticipantMap expected,
        ShipmentParticipantMap actual
    ) {
        assertShipmentParticipantMapUpdatableFieldsEquals(expected, actual);
        assertShipmentParticipantMapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentParticipantMapAutoGeneratedPropertiesEquals(
        ShipmentParticipantMap expected,
        ShipmentParticipantMap actual
    ) {
        assertThat(actual)
            .as("Verify ShipmentParticipantMap auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentParticipantMapUpdatableFieldsEquals(ShipmentParticipantMap expected, ShipmentParticipantMap actual) {
        assertThat(actual)
            .as("Verify ShipmentParticipantMap relevant properties")
            .satisfies(a -> assertThat(a.getResponseStatus()).as("check responseStatus").isEqualTo(expected.getResponseStatus()))
            .satisfies(a ->
                assertThat(a.getShipmentReceiptDate()).as("check shipmentReceiptDate").isEqualTo(expected.getShipmentReceiptDate())
            )
            .satisfies(a -> assertThat(a.getShipmentTestDate()).as("check shipmentTestDate").isEqualTo(expected.getShipmentTestDate()))
            .satisfies(a ->
                assertThat(a.getShipmentTestReportDate()).as("check shipmentTestReportDate").isEqualTo(expected.getShipmentTestReportDate())
            )
            .satisfies(a -> assertThat(a.getSubmittedAt()).as("check submittedAt").isEqualTo(expected.getSubmittedAt()))
            .satisfies(a -> assertThat(a.getEvaluatedAt()).as("check evaluatedAt").isEqualTo(expected.getEvaluatedAt()))
            .satisfies(a -> assertThat(a.getIsExcluded()).as("check isExcluded").isEqualTo(expected.getIsExcluded()))
            .satisfies(a -> assertThat(a.getIsResponseLate()).as("check isResponseLate").isEqualTo(expected.getIsResponseLate()))
            .satisfies(a ->
                assertThat(a.getIsPtTestNotPerformed()).as("check isPtTestNotPerformed").isEqualTo(expected.getIsPtTestNotPerformed())
            )
            .satisfies(a ->
                assertThat(a.getPtTestNotPerformedComments())
                    .as("check ptTestNotPerformedComments")
                    .isEqualTo(expected.getPtTestNotPerformedComments())
            )
            .satisfies(a ->
                assertThat(a.getSupervisorApproved()).as("check supervisorApproved").isEqualTo(expected.getSupervisorApproved())
            )
            .satisfies(a ->
                assertThat(a.getParticipantSupervisor()).as("check participantSupervisor").isEqualTo(expected.getParticipantSupervisor())
            )
            .satisfies(a -> assertThat(a.getUserComment()).as("check userComment").isEqualTo(expected.getUserComment()))
            .satisfies(a -> assertThat(a.getShipmentScore()).as("check shipmentScore").isEqualTo(expected.getShipmentScore()))
            .satisfies(a ->
                assertThat(a.getDocumentationScore()).as("check documentationScore").isEqualTo(expected.getDocumentationScore())
            )
            .satisfies(a -> assertThat(a.getFinalResult()).as("check finalResult").isEqualTo(expected.getFinalResult()))
            .satisfies(a -> assertThat(a.getFailureReason()).as("check failureReason").isEqualTo(expected.getFailureReason()))
            .satisfies(a -> assertThat(a.getEvaluationComment()).as("check evaluationComment").isEqualTo(expected.getEvaluationComment()))
            .satisfies(a -> assertThat(a.getIsFollowup()).as("check isFollowup").isEqualTo(expected.getIsFollowup()))
            .satisfies(a -> assertThat(a.getManualOverride()).as("check manualOverride").isEqualTo(expected.getManualOverride()))
            .satisfies(a -> assertThat(a.getQcStatus()).as("check qcStatus").isEqualTo(expected.getQcStatus()))
            .satisfies(a -> assertThat(a.getQcDate()).as("check qcDate").isEqualTo(expected.getQcDate()))
            .satisfies(a -> assertThat(a.getQcDoneBy()).as("check qcDoneBy").isEqualTo(expected.getQcDoneBy()))
            .satisfies(a -> assertThat(a.getSyncedToMobile()).as("check syncedToMobile").isEqualTo(expected.getSyncedToMobile()))
            .satisfies(a -> assertThat(a.getSyncedOn()).as("check syncedOn").isEqualTo(expected.getSyncedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentParticipantMapUpdatableRelationshipsEquals(
        ShipmentParticipantMap expected,
        ShipmentParticipantMap actual
    ) {
        assertThat(actual)
            .as("Verify ShipmentParticipantMap relationships")
            .satisfies(a -> assertThat(a.getModeOfReceipt()).as("check modeOfReceipt").isEqualTo(expected.getModeOfReceipt()))
            .satisfies(a -> assertThat(a.getNotTestedReason()).as("check notTestedReason").isEqualTo(expected.getNotTestedReason()))
            .satisfies(a -> assertThat(a.getShipment()).as("check shipment").isEqualTo(expected.getShipment()))
            .satisfies(a -> assertThat(a.getParticipant()).as("check participant").isEqualTo(expected.getParticipant()));
    }
}
