package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentSampleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentSampleAllPropertiesEquals(ShipmentSample expected, ShipmentSample actual) {
        assertShipmentSampleAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentSampleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentSampleAllUpdatablePropertiesEquals(ShipmentSample expected, ShipmentSample actual) {
        assertShipmentSampleUpdatableFieldsEquals(expected, actual);
        assertShipmentSampleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentSampleAutoGeneratedPropertiesEquals(ShipmentSample expected, ShipmentSample actual) {
        assertThat(actual)
            .as("Verify ShipmentSample auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentSampleUpdatableFieldsEquals(ShipmentSample expected, ShipmentSample actual) {
        assertThat(actual)
            .as("Verify ShipmentSample relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getIsControl()).as("check isControl").isEqualTo(expected.getIsControl()))
            .satisfies(a -> assertThat(a.getIsMandatory()).as("check isMandatory").isEqualTo(expected.getIsMandatory()))
            .satisfies(a -> assertThat(a.getSampleScore()).as("check sampleScore").isEqualTo(expected.getSampleScore()))
            .satisfies(a -> assertThat(a.getPreparationDate()).as("check preparationDate").isEqualTo(expected.getPreparationDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentSampleUpdatableRelationshipsEquals(ShipmentSample expected, ShipmentSample actual) {
        assertThat(actual)
            .as("Verify ShipmentSample relationships")
            .satisfies(a -> assertThat(a.getShipment()).as("check shipment").isEqualTo(expected.getShipment()));
    }
}
