package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAllPropertiesEquals(Shipment expected, Shipment actual) {
        assertShipmentAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAllUpdatablePropertiesEquals(Shipment expected, Shipment actual) {
        assertShipmentUpdatableFieldsEquals(expected, actual);
        assertShipmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAutoGeneratedPropertiesEquals(Shipment expected, Shipment actual) {
        assertThat(actual)
            .as("Verify Shipment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentUpdatableFieldsEquals(Shipment expected, Shipment actual) {
        assertThat(actual)
            .as("Verify Shipment relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getShipmentDate()).as("check shipmentDate").isEqualTo(expected.getShipmentDate()))
            .satisfies(a -> assertThat(a.getResponseDeadline()).as("check responseDeadline").isEqualTo(expected.getResponseDeadline()))
            .satisfies(a -> assertThat(a.getResponsesOpen()).as("check responsesOpen").isEqualTo(expected.getResponsesOpen()))
            .satisfies(a ->
                assertThat(a.getAutoCloseAtDeadline()).as("check autoCloseAtDeadline").isEqualTo(expected.getAutoCloseAtDeadline())
            )
            .satisfies(a ->
                assertThat(a.getAllowEditingResponse()).as("check allowEditingResponse").isEqualTo(expected.getAllowEditingResponse())
            )
            .satisfies(a -> assertThat(a.getIssuingAuthority()).as("check issuingAuthority").isEqualTo(expected.getIssuingAuthority()))
            .satisfies(a -> assertThat(a.getCoordinatorName()).as("check coordinatorName").isEqualTo(expected.getCoordinatorName()))
            .satisfies(a -> assertThat(a.getCoordinatorEmail()).as("check coordinatorEmail").isEqualTo(expected.getCoordinatorEmail()))
            .satisfies(a -> assertThat(a.getCoordinatorPhone()).as("check coordinatorPhone").isEqualTo(expected.getCoordinatorPhone()))
            .satisfies(a -> assertThat(a.getNumberOfSamples()).as("check numberOfSamples").isEqualTo(expected.getNumberOfSamples()))
            .satisfies(a -> assertThat(a.getMaxScore()).as("check maxScore").isEqualTo(expected.getMaxScore()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAttributes()).as("check attributes").isEqualTo(expected.getAttributes()))
            .satisfies(a ->
                assertThat(a.getReportsGeneratedAt()).as("check reportsGeneratedAt").isEqualTo(expected.getReportsGeneratedAt())
            )
            .satisfies(a -> assertThat(a.getFinalizedAt()).as("check finalizedAt").isEqualTo(expected.getFinalizedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentUpdatableRelationshipsEquals(Shipment expected, Shipment actual) {
        assertThat(actual)
            .as("Verify Shipment relationships")
            .satisfies(a -> assertThat(a.getDistribution()).as("check distribution").isEqualTo(expected.getDistribution()))
            .satisfies(a -> assertThat(a.getScheme()).as("check scheme").isEqualTo(expected.getScheme()))
            .satisfies(a ->
                assertThat(a.getCertificateBatcheses()).as("check certificateBatcheses").isEqualTo(expected.getCertificateBatcheses())
            );
    }
}
