package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TestKitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestKitAllPropertiesEquals(TestKit expected, TestKit actual) {
        assertTestKitAutoGeneratedPropertiesEquals(expected, actual);
        assertTestKitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestKitAllUpdatablePropertiesEquals(TestKit expected, TestKit actual) {
        assertTestKitUpdatableFieldsEquals(expected, actual);
        assertTestKitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestKitAutoGeneratedPropertiesEquals(TestKit expected, TestKit actual) {
        assertThat(actual)
            .as("Verify TestKit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestKitUpdatableFieldsEquals(TestKit expected, TestKit actual) {
        assertThat(actual)
            .as("Verify TestKit relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getManufacturer()).as("check manufacturer").isEqualTo(expected.getManufacturer()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestKitUpdatableRelationshipsEquals(TestKit expected, TestKit actual) {
        assertThat(actual)
            .as("Verify TestKit relationships")
            .satisfies(a -> assertThat(a.getScheme()).as("check scheme").isEqualTo(expected.getScheme()));
    }
}
