package zw.org.nmrl.ept.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserLoginHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLoginHistoryAllPropertiesEquals(UserLoginHistory expected, UserLoginHistory actual) {
        assertUserLoginHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertUserLoginHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLoginHistoryAllUpdatablePropertiesEquals(UserLoginHistory expected, UserLoginHistory actual) {
        assertUserLoginHistoryUpdatableFieldsEquals(expected, actual);
        assertUserLoginHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLoginHistoryAutoGeneratedPropertiesEquals(UserLoginHistory expected, UserLoginHistory actual) {
        assertThat(actual)
            .as("Verify UserLoginHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLoginHistoryUpdatableFieldsEquals(UserLoginHistory expected, UserLoginHistory actual) {
        assertThat(actual)
            .as("Verify UserLoginHistory relevant properties")
            .satisfies(a -> assertThat(a.getLoginId()).as("check loginId").isEqualTo(expected.getLoginId()))
            .satisfies(a -> assertThat(a.getLoginContext()).as("check loginContext").isEqualTo(expected.getLoginContext()))
            .satisfies(a -> assertThat(a.getLoginStatus()).as("check loginStatus").isEqualTo(expected.getLoginStatus()))
            .satisfies(a -> assertThat(a.getAttemptedAt()).as("check attemptedAt").isEqualTo(expected.getAttemptedAt()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getBrowser()).as("check browser").isEqualTo(expected.getBrowser()))
            .satisfies(a -> assertThat(a.getOperatingSystem()).as("check operatingSystem").isEqualTo(expected.getOperatingSystem()))
            .satisfies(a -> assertThat(a.getSessionHash()).as("check sessionHash").isEqualTo(expected.getSessionHash()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLoginHistoryUpdatableRelationshipsEquals(UserLoginHistory expected, UserLoginHistory actual) {
        // empty method
    }
}
