export enum CertificateBatchStatus {
  PENDING = 'PENDING',

  GENERATING = 'GENERATING',

  GENERATED = 'GENERATED',

  APPROVED = 'APPROVED',

  DISTRIBUTING = 'DISTRIBUTING',

  DISTRIBUTED = 'DISTRIBUTED',

  FAILED = 'FAILED',
}
